apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitops2acr.azurecr.io/azvote/azure-vote-front
    newTag: fd2dd5225705ff97bcb9d1912dfbe6572445927b
  - name: gitops2acr.azurecr.io/azvote/azure-vote-back
    newTag: fd2dd5225705ff97bcb9d1912dfbe6572445927b
resources:
  - manifests.yaml