apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitops2acr.azurecr.io/azure-vote-front
    newTag: 1d91566faa8cc293540ffbb0ea30444e167ee841
  - name: gitops2acr.azurecr.io/azure-vote-back
    newTag: 1d91566faa8cc293540ffbb0ea30444e167ee841
resources:
  - manifests.yaml