apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitops2acr.azurecr.io/azure-vote-front
    newTag: 5b2269882c4b600f1c6e3fc298c03cd42773c694
  - name: gitops2acr.azurecr.io/azure-vote-back
    newTag: 5b2269882c4b600f1c6e3fc298c03cd42773c694
resources:
  - manifests.yaml