apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitops2acr.azurecr.io/azvote/azure-vote-front
    newTag: 389162e0380034f0f9153cf418c71990d40524ac
  - name: gitops2acr.azurecr.io/azvote/azure-vote-back
    newTag: 389162e0380034f0f9153cf418c71990d40524ac
resources:
  - manifests.yaml