apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitops2acr.azurecr.io/azvote/azure-vote-front
    newTag: cf101e4654d061c271866c8df3f7e4ea7d248746
  - name: gitops2acr.azurecr.io/azvote/azure-vote-back
    newTag: cf101e4654d061c271866c8df3f7e4ea7d248746
resources:
  - manifests.yaml