apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitops2acr.azurecr.io/azvote/azure-vote-front
    newTag: 310fd76854125a9cf25e279f26dbd80ec7621704
  - name: gitops2acr.azurecr.io/azvote/azure-vote-back
    newTag: 310fd76854125a9cf25e279f26dbd80ec7621704
resources:
  - manifests.yaml