apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitops2acr.azurecr.io/azvote/azure-vote-front
    newTag: cda6c730cbbf47dfba790a7f49cf4323c85e38bc
  - name: gitops2acr.azurecr.io/azvote/azure-vote-back
    newTag: cda6c730cbbf47dfba790a7f49cf4323c85e38bc
resources:
  - manifests.yaml